columnSuffix: zbdridai
contentColumnType: time
fieldGroup: 15aca9d8-3109-47f8-b2d9-c1c474a09489 # Openingsuren
handle: eind
instructions: null
name: eind
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
