columnSuffix: twdkcbnf
contentColumnType: integer(10)
fieldGroup: b04bcee3-447a-4b35-b88b-43b89be444a0 # zadel
handle: gewichtAccessoire
instructions: null
name: 'Gewicht accessoire'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: KG
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
