columnSuffix: vxwpvshm
contentColumnType: integer(10)
fieldGroup: 3d9dfd4a-eed7-47ec-b7f6-485273913bf4 # Bikes
handle: gewicht
instructions: null
name: Gewicht
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: KG
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
