columnSuffix: mddsbtgs
contentColumnType: integer(10)
fieldGroup: 7fe5120c-a9cc-44f5-8a2b-da4c27ae4bea # Address
handle: huisnummer
instructions: null
name: Huisnummer
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
