columnSuffix: null
contentColumnType: string
fieldGroup: 3d9dfd4a-eed7-47ec-b7f6-485273913bf4 # Bikes
handle: motor
instructions: null
name: Motor
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:5e2d739a-8eed-41a8-b595-c4008b49e8d2' # Motor
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
