columnSuffix: fvauwqcd
contentColumnType: text
fieldGroup: 39f65184-bd4f-4339-8f32-b4e44ed38fc1 # Gebruiker
handle: naam
instructions: null
name: Naam
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
