columnSuffix: null
contentColumnType: string
fieldGroup: 3d9dfd4a-eed7-47ec-b7f6-485273913bf4 # Bikes
handle: typefiets
instructions: null
name: Type
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:6c7c0bda-4e4a-4425-9aad-fd6812906938' # Submerk
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
