handle: stripe
isFrontendEnabled: '1'
name: stripe
paymentType: purchase
settings:
  apiKey: sk_test_51OqLzRHujSNn239Ok3QNbIaCudyHZD9vSSUIkrZnlgsercJvzXBhwDa1DEJQT1dPuYyzZxmbNAIvMT8Q0ZhjrkTR00yocBShTu
  publishableKey: pk_test_51OqLzRHujSNn239OlRrA7P8bf1arC1KMLRN9L5j5SG3LNTyQJRfF36YTuVr7HQ1dkpKhX42d12YOaRaWq3T486Ko00EY7egtN6
  sendReceiptEmail: false
  signingSecret: ''
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
