siteUid: null
sortOrder: 3
template: ''
uriParts:
  - 'http://localhost/2023-2024-atelier4-bs-groep4/bikestore/web/bikes/bike'
uriPattern: 'http://localhost/2023-2024-atelier4-bs-groep4/bikestore/web/bikes/bike'
