field: 25a2e0cf-475e-4acc-a7ad-b5f52c5fa4be # Product colours
fieldLayouts:
  3a9e1a1f-2550-4be0-9835-031b357078bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 77d9208d-916a-41f9-a664-810d6a4bd48d # Light blue
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9a2755b-17eb-4d63-82f4-80e13870e68c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6000aec3-476f-425f-896b-1d4ce1219b4b
        userCondition: null
fields:
  77d9208d-916a-41f9-a664-810d6a4bd48d: # Light blue
    columnSuffix: fjtvjpeo
    contentColumnType: char(7)
    fieldGroup: null
    handle: lightBlue
    instructions: null
    name: 'Light blue'
    searchable: false
    settings:
      defaultColor: '#546d8b'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
handle: lightBlue
name: 'Light blue'
sortOrder: 1
