fieldLayouts:
  5d25faee-7569-47bb-b50b-98895b3ad7b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 00d1d7bb-7782-4c36-be3b-d7ef4dca4a84 # navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80edaac2-2c39-4079-b6cf-72105d068942
            userCondition: null
            warning: null
            width: 100
        name: navigation
        uid: 54a95cf1-416b-4bd5-8e5d-5d60ea838424
        userCondition: null
handle: footerNavigatieKlantendienst
name: 'footer navigatie klantendienst'
sortOrder: 12
