fieldLayouts:
  c5b6fb7e-49b5-408b-87da-430de8af8859:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 00d1d7bb-7782-4c36-be3b-d7ef4dca4a84 # navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b9a255d-0244-4147-b68d-a0f4283fcc6d
            userCondition: null
            warning: null
            width: 100
        name: navigation
        uid: d4b9d54b-d630-4e14-a771-16a138e6c34f
        userCondition: null
handle: footerNavigatieAanbod
name: 'footer navigatie aanbod'
sortOrder: 10
