fieldLayouts:
  36884e2e-a329-4ab2-9dda-ae8e299f310a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 39f020ca-d842-4a11-a1ea-7e088c7fc417
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5b91cb7-334f-431f-af73-253e820af38c # url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd57c583-113f-417b-ba33-a8a89f1463ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 689e1a34-ab18-46a3-a3e2-ad5ac5f08d20
        userCondition: null
handle: Aanbod
hasTitleField: true
name: Aanbod
section: 0e1d56a1-1c5a-417d-8124-827f28768003 # Aanbod
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
