fieldLayouts:
  07b24bd2-3fcb-447d-9e5f-99e7e3a75492:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5902c14d-aa31-4d64-9310-5293f256ec0e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6fc83721-c527-42e6-9a36-687df38d9ef4 # urlKlanten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8bea23b-7790-443d-9edb-5f8a5ad1828a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a617b86-528c-4edf-8986-50fb02b39e37
        userCondition: null
handle: klantendienst
hasTitleField: true
name: Klantendienst
section: fa509277-0e67-4286-8d32-c770257bec56 # Klantendienst
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
