fieldLayouts:
  5547c3e3-02f7-47ef-81d0-1eb094ad1625:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c605ad4e-e6c9-46db-a852-16b94f157858
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3a0d62e-7656-4af3-8ff8-5ba64e4b8d0b # Open/gesloten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b49b75c1-1756-4083-ba6d-ae1778e1ee6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01b96a17-7164-4ba6-9432-2b730d81039c # start
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e82df72-0d9f-47d9-80d4-f32b229195b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf664faf-e944-444c-afcd-a71645868c98 # eind
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bda6d9d5-3f6b-48ec-aa4a-dd23d1257c79
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c4959a6-5f2b-4c8e-8ab9-1738c80fadd2
        userCondition: null
handle: openingsuren
hasTitleField: true
name: Openingsuren
section: 248aecbe-33c9-46da-b29d-307d15b7ecf9 # Openingsuren
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
