fieldLayouts:
  64deffd2-f670-4391-83f7-27ec08a4f6e5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f48ccadd-fa97-4aa9-a7f8-0c8a50309f05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78460aa0-e8f0-4c2c-a4fa-0630ac0844d6 # Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0bc69bd-c6d2-450f-8483-acd033ae379a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d41df2d-2d6b-400e-b00e-7e60f9ccd3d8
        userCondition: null
handle: topNav
hasTitleField: true
name: Topnav
section: b8efbb71-a113-45b3-90e7-5b4e7a62c264
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
