defaultPlacement: end
enableVersioning: true
handle: assortiment
name: Assortiment
propagationMethod: all
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    enabledByDefault: true
    hasUrls: true
    template: assortiment/_entry
    uriFormat: assortiment
type: single
