defaultPlacement: end
enableVersioning: true
handle: bikeEntries
name: Bikes
propagationMethod: all
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    enabledByDefault: true
    hasUrls: true
    template: bikes/_entry
    uriFormat: 'bikes/{slug}'
type: channel
