defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: blog
type: single
