defaultPlacement: end
enableVersioning: true
handle: faq
name: FAQ
propagationMethod: all
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    enabledByDefault: true
    hasUrls: true
    template: faq/_entry
    uriFormat: 'faq/{slug}'
structure:
  maxLevels: null
  uid: 7b006a96-0f6c-45d5-889f-e2351b54ce99
type: structure
