defaultPlacement: end
enableVersioning: true
handle: openingsuren
name: Openingsuren
propagationMethod: all
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    enabledByDefault: true
    hasUrls: true
    template: openingsuren/_entry
    uriFormat: 'openingsuren/{slug}'
structure:
  maxLevels: null
  uid: 8f47c63e-ff6e-4b10-ac21-3f254e6a99b0
type: structure
