defaultPlacement: end
enableVersioning: true
handle: topNavigation
name: Top-navigation
propagationMethod: all
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    enabledByDefault: true
    hasUrls: true
    template: top-navigation/_entry
    uriFormat: 'top-navigation/{slug}'
structure:
  maxLevels: null
  uid: 5cd4027f-d6d8-426e-944a-a3cf48f3ec64
type: structure
