defaultPlacement: end
fieldLayouts:
  f62faf10-7e82-446c-bb80-04af465f405d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c45ed0e1-f8d8-488d-8a60-f38386f2d85f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fb628187-fb4b-43cd-9884-67ca50dbef38 # URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03a6ea40-0e90-4b13-8a59-1973545b0a5e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 544ca443-af1c-4656-b399-3467e2f10436
        userCondition: null
handle: frametype
name: Frametype
siteSettings:
  221550b7-fdd7-44be-9c04-f94cffd8e187: # bikestore
    hasUrls: true
    template: null
    uriFormat: 'fietsen/{slug}'
structure:
  maxLevels: null
  uid: 87db3a37-0320-4c38-ac05-5f49ffa4559b
